name: App Checks

on:
  - push

env:
  NEXT_PUBLIC_BETTER_AUTH_URL: http://localhost:3000
  PG_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

jobs:
  type_build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 10
          run_install: true
      - run: |
          pnpm check
          pnpm build
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - uses: pnpm/action-setup@v3
  #       name: Install pnpm
  #       with:
  #         version: 10
  #         run_install: true
  #     - run: |
  #         pnpm test
