name: Check Merge Conflicts

on:
  pull_request:
    branches:
      - main

jobs:
  check-conflicts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check for merge conflicts
        run: |
          git checkout main
          git merge --no-commit --no-ff ${{ github.event.pull_request.head.sha }} || echo "::error::Merge conflict detected!"
